// Shared palette + index→color generator used wherever the app needs a
// distinct color per item in a growing list (narrative strands, character
// groups). The first 10 indices return the curated palette so the picker
// swatches stay "active" for common projects; beyond that, hues are
// generated by golden-angle (137.508°) rotation so any N stays maximally
// distinct without wrapping back to duplicates.
//
// Lightness/chroma are clamped at oklch(0.65 0.13 …) so generated hues
// sit in the same perceptual band as the curated palette — strand 47
// reads as "the same kind of color" as strand 3, just a different hue.

export const PALETTE = [
  "oklch(0.65 0.13 25)",   "oklch(0.65 0.13 5)",    "oklch(0.65 0.13 330)",
  "oklch(0.65 0.13 290)",  "oklch(0.65 0.13 250)",  "oklch(0.65 0.13 210)",
  "oklch(0.65 0.13 170)",  "oklch(0.65 0.13 130)",  "oklch(0.65 0.13 95)",
  "oklch(0.7 0.13 55)",
];

const GOLDEN_ANGLE = 137.508;
// Seed the generator after the last curated hue (55°) so overflow #1
// lands somewhere visually distinct from the curated set's near-warm end.
const OVERFLOW_SEED = 13;

export function nextColor(index) {
  if (index < PALETTE.length) return PALETTE[index];
  const overflow = index - PALETTE.length;
  const hue = (OVERFLOW_SEED + overflow * GOLDEN_ANGLE) % 360;
  return `oklch(0.65 0.13 ${hue.toFixed(1)})`;
}
