// SPDX-License-Identifier: MIT
// GENERATED by scripts/capture-schema.py from justwrite_server.database.models:Base — do not edit by hand.
// Each table's DDL is the exact text Python's create_all writes to sqlite_master;
// `columns` carries what lives in Python, not the database: the conversion kind and
// the Python-side defaults. Re-generate when a Python table changes.
export const TABLES = [
  {
    "name": "settings",
    "ddl": "CREATE TABLE settings (\n\t\"key\" VARCHAR NOT NULL, \n\tvalue TEXT NOT NULL, \n\tPRIMARY KEY (\"key\")\n)",
    "indexes": [],
    "columns": {
      "key": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "value": {
        "kind": "text",
        "notNull": true,
        "default": "null"
      }
    }
  },
  {
    "name": "projects",
    "ddl": "CREATE TABLE projects (\n\tid VARCHAR NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tauthor VARCHAR NOT NULL, \n\tsubtitle VARCHAR NOT NULL, \n\tgenre VARCHAR NOT NULL, \n\twords_goal INTEGER NOT NULL, \n\tdaily_target INTEGER NOT NULL, \n\twords_written INTEGER NOT NULL, \n\tstarted_on VARCHAR NOT NULL, \n\tdeadline VARCHAR NOT NULL, \n\tpremise TEXT NOT NULL, \n\tworld_rules TEXT NOT NULL, \n\tcover_image TEXT, \n\tupdated_at VARCHAR NOT NULL, \n\tdata TEXT NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "indexes": [],
    "columns": {
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": "Untitled"
      },
      "author": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "subtitle": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "genre": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "words_goal": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "daily_target": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "words_written": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "started_on": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "deadline": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "premise": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "world_rules": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "cover_image": {
        "kind": "text"
      },
      "updated_at": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "data": {
        "kind": "text",
        "notNull": true,
        "default": "{}"
      }
    }
  },
  {
    "name": "rag_meta",
    "ddl": "CREATE TABLE rag_meta (\n\tproject_id VARCHAR NOT NULL, \n\tmodel VARCHAR NOT NULL, \n\tdims INTEGER NOT NULL, \n\tPRIMARY KEY (project_id)\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "model": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "dims": {
        "kind": "int",
        "notNull": true,
        "default": 0
      }
    }
  },
  {
    "name": "rag_vectors",
    "ddl": "CREATE TABLE rag_vectors (\n\tproject_id VARCHAR NOT NULL, \n\tchunk_id VARCHAR NOT NULL, \n\tsha VARCHAR NOT NULL, \n\tvector TEXT NOT NULL, \n\tchunk TEXT NOT NULL, \n\tPRIMARY KEY (project_id, chunk_id)\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "chunk_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "sha": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "vector": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      },
      "chunk": {
        "kind": "text",
        "notNull": true,
        "default": "{}"
      }
    }
  },
  {
    "name": "image_blobs",
    "ddl": "CREATE TABLE image_blobs (\n\tid VARCHAR NOT NULL, \n\tname VARCHAR NOT NULL, \n\tmime VARCHAR NOT NULL, \n\tdata BLOB NOT NULL, \n\tcreated_at VARCHAR NOT NULL, \n\tPRIMARY KEY (id)\n)",
    "indexes": [],
    "columns": {
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "name": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "mime": {
        "kind": "text",
        "notNull": true,
        "default": "application/octet-stream"
      },
      "data": {
        "kind": "blob",
        "notNull": true
      },
      "created_at": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "sessions",
    "ddl": "CREATE TABLE sessions (\n\tday VARCHAR NOT NULL, \n\twords INTEGER NOT NULL, \n\tPRIMARY KEY (day)\n)",
    "indexes": [],
    "columns": {
      "day": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "words": {
        "kind": "int",
        "notNull": true,
        "default": 0
      }
    }
  },
  {
    "name": "session_chapter_words",
    "ddl": "CREATE TABLE session_chapter_words (\n\tchapter_id VARCHAR NOT NULL, \n\twords INTEGER NOT NULL, \n\tPRIMARY KEY (chapter_id)\n)",
    "indexes": [],
    "columns": {
      "chapter_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "words": {
        "kind": "int",
        "notNull": true,
        "default": 0
      }
    }
  },
  {
    "name": "session_meta",
    "ddl": "CREATE TABLE session_meta (\n\tid VARCHAR NOT NULL, \n\tlast_write_chapter VARCHAR, \n\tlast_write_day VARCHAR, \n\tPRIMARY KEY (id)\n)",
    "indexes": [],
    "columns": {
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true,
        "default": "singleton"
      },
      "last_write_chapter": {
        "kind": "text"
      },
      "last_write_day": {
        "kind": "text"
      }
    }
  },
  {
    "name": "parts",
    "ddl": "CREATE TABLE parts (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "chapters",
    "ddl": "CREATE TABLE chapters (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tpart_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tnum INTEGER NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\twords INTEGER NOT NULL, \n\tstatus VARCHAR NOT NULL, \n\tis_voice_canon BOOLEAN NOT NULL, \n\tcritique TEXT, \n\treader_knowledge TEXT, \n\tmulti_reader TEXT, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "part_id": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "num": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "words": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "status": {
        "kind": "text",
        "notNull": true,
        "default": "todo"
      },
      "is_voice_canon": {
        "kind": "bool",
        "notNull": true,
        "default": false
      },
      "critique": {
        "kind": "text"
      },
      "reader_knowledge": {
        "kind": "text"
      },
      "multi_reader": {
        "kind": "text"
      }
    }
  },
  {
    "name": "scenes",
    "ddl": "CREATE TABLE scenes (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tchapter_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tbody TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "chapter_id": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "body": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "scene_links",
    "ddl": "CREATE TABLE scene_links (\n\tproject_id VARCHAR NOT NULL, \n\tscene_id VARCHAR NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tref_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tPRIMARY KEY (project_id, scene_id, kind, ref_id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "scene_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "kind": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "ref_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      }
    }
  },
  {
    "name": "chapter_strands",
    "ddl": "CREATE TABLE chapter_strands (\n\tproject_id VARCHAR NOT NULL, \n\tchapter_id VARCHAR NOT NULL, \n\tstrand_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tPRIMARY KEY (project_id, chapter_id, strand_id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "chapter_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "strand_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      }
    }
  },
  {
    "name": "group_members",
    "ddl": "CREATE TABLE group_members (\n\tproject_id VARCHAR NOT NULL, \n\tgroup_id VARCHAR NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tref_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tPRIMARY KEY (project_id, group_id, kind, ref_id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "group_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "kind": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "ref_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      }
    }
  },
  {
    "name": "characters",
    "ddl": "CREATE TABLE characters (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tname VARCHAR NOT NULL, \n\tmain BOOLEAN NOT NULL, \n\tage INTEGER, \n\tgender VARCHAR NOT NULL, \n\tpronouns VARCHAR NOT NULL, \n\tlife_status VARCHAR NOT NULL, \n\tone_liner TEXT NOT NULL, \n\trole VARCHAR NOT NULL, \n\taliases TEXT NOT NULL, \n\ttags TEXT NOT NULL, \n\textras TEXT, \n\taudit TEXT, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "name": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "main": {
        "kind": "bool",
        "notNull": true,
        "default": false
      },
      "age": {
        "kind": "int"
      },
      "gender": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "pronouns": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "life_status": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "one_liner": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "role": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "aliases": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      },
      "tags": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      },
      "extras": {
        "kind": "text"
      },
      "audit": {
        "kind": "text"
      }
    }
  },
  {
    "name": "locations",
    "ddl": "CREATE TABLE locations (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tname VARCHAR NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tnote TEXT NOT NULL, \n\ttags TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "name": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "kind": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "note": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "tags": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      }
    }
  },
  {
    "name": "objects",
    "ddl": "CREATE TABLE objects (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tname VARCHAR NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tnote TEXT NOT NULL, \n\ttags TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "name": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "kind": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "note": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "tags": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      }
    }
  },
  {
    "name": "groups",
    "ddl": "CREATE TABLE groups (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tname VARCHAR NOT NULL, \n\tblurb TEXT NOT NULL, \n\tcolor VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "name": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "blurb": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "color": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "notes",
    "ddl": "CREATE TABLE notes (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tbody TEXT NOT NULL, \n\ttag VARCHAR NOT NULL, \n\tupdated VARCHAR NOT NULL, \n\tanchor_chapter_id VARCHAR, \n\tanchor_scene_id VARCHAR, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "body": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "tag": {
        "kind": "text",
        "notNull": true,
        "default": "note"
      },
      "updated": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "anchor_chapter_id": {
        "kind": "text"
      },
      "anchor_scene_id": {
        "kind": "text"
      }
    }
  },
  {
    "name": "strands",
    "ddl": "CREATE TABLE strands (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tname VARCHAR NOT NULL, \n\tcolor VARCHAR NOT NULL, \n\tblurb TEXT NOT NULL, \n\tbody TEXT NOT NULL, \n\tstatus VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "name": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "color": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "blurb": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "body": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "status": {
        "kind": "text",
        "notNull": true,
        "default": "open"
      }
    }
  },
  {
    "name": "strand_beats",
    "ddl": "CREATE TABLE strand_beats (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tstrand_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tchapter_id VARCHAR, \n\tscene_id VARCHAR, \n\tlabel VARCHAR NOT NULL, \n\tnote TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "strand_id": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "chapter_id": {
        "kind": "text"
      },
      "scene_id": {
        "kind": "text"
      },
      "label": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "note": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "worldbuilding",
    "ddl": "CREATE TABLE worldbuilding (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tcategory_id VARCHAR NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tstatus VARCHAR NOT NULL, \n\twords INTEGER NOT NULL, \n\tsummary TEXT NOT NULL, \n\tbody TEXT NOT NULL, \n\ttags TEXT NOT NULL, \n\trelated TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "category_id": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "status": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "words": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "summary": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "body": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "tags": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      },
      "related": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      }
    }
  },
  {
    "name": "worldbuilding_categories",
    "ddl": "CREATE TABLE worldbuilding_categories (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tlabel VARCHAR NOT NULL, \n\ticon VARCHAR NOT NULL, \n\thue INTEGER NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "label": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "icon": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "hue": {
        "kind": "int",
        "notNull": true,
        "default": 0
      }
    }
  },
  {
    "name": "statuses",
    "ddl": "CREATE TABLE statuses (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tlabel VARCHAR NOT NULL, \n\tcolor VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "label": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "color": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "tag_vocab",
    "ddl": "CREATE TABLE tag_vocab (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tlabel VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "kind": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "label": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "architecture",
    "ddl": "CREATE TABLE architecture (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tstatus VARCHAR NOT NULL, \n\twords INTEGER NOT NULL, \n\tbody TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "status": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "words": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "body": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "images",
    "ddl": "CREATE TABLE images (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tentity_kind VARCHAR NOT NULL, \n\tentity_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tadded_at INTEGER, \n\tdata TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "entity_kind": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "entity_id": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "added_at": {
        "kind": "int"
      },
      "data": {
        "kind": "text",
        "notNull": true,
        "default": "{}"
      }
    }
  },
  {
    "name": "events",
    "ddl": "CREATE TABLE events (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tentity_kind VARCHAR NOT NULL, \n\tentity_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\t\"when\" VARCHAR NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tnote TEXT NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "entity_kind": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "entity_id": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "when": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "note": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "project_artifacts",
    "ddl": "CREATE TABLE project_artifacts (\n\tproject_id VARCHAR NOT NULL, \n\tkind VARCHAR NOT NULL, \n\t\"key\" VARCHAR NOT NULL, \n\tdata TEXT NOT NULL, \n\tupdated_at VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id, kind, \"key\"), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "kind": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "key": {
        "kind": "text",
        "pk": true,
        "notNull": true,
        "default": ""
      },
      "data": {
        "kind": "text",
        "notNull": true,
        "default": "{}"
      },
      "updated_at": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "trash",
    "ddl": "CREATE TABLE trash (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tkind VARCHAR NOT NULL, \n\tpayload TEXT NOT NULL, \n\tdeleted_at INTEGER, \n\tPRIMARY KEY (project_id, id, kind), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "kind": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "payload": {
        "kind": "text",
        "notNull": true,
        "default": "{}"
      },
      "deleted_at": {
        "kind": "int"
      }
    }
  },
  {
    "name": "chat_sessions",
    "ddl": "CREATE TABLE chat_sessions (\n\tproject_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tmode VARCHAR NOT NULL, \n\tcharacter_id VARCHAR NOT NULL, \n\ttitle VARCHAR NOT NULL, \n\tupdated_at VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "mode": {
        "kind": "text",
        "notNull": true,
        "default": "book"
      },
      "character_id": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "title": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "updated_at": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  },
  {
    "name": "chat_session_messages",
    "ddl": "CREATE TABLE chat_session_messages (\n\tproject_id VARCHAR NOT NULL, \n\tsession_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\trole VARCHAR NOT NULL, \n\tcontent TEXT NOT NULL, \n\tcitations TEXT NOT NULL, \n\terror TEXT, \n\tPRIMARY KEY (project_id, session_id, position), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "session_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "pk": true,
        "notNull": true
      },
      "role": {
        "kind": "text",
        "notNull": true,
        "default": "user"
      },
      "content": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "citations": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      },
      "error": {
        "kind": "text"
      }
    }
  },
  {
    "name": "chat_messages",
    "ddl": "CREATE TABLE chat_messages (\n\tproject_id VARCHAR NOT NULL, \n\tmode VARCHAR NOT NULL, \n\tcharacter_id VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\trole VARCHAR NOT NULL, \n\tcontent TEXT NOT NULL, \n\tcitations TEXT NOT NULL, \n\terror TEXT, \n\tPRIMARY KEY (project_id, mode, character_id, position), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "mode": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "character_id": {
        "kind": "text",
        "pk": true,
        "notNull": true,
        "default": ""
      },
      "position": {
        "kind": "int",
        "pk": true,
        "notNull": true
      },
      "role": {
        "kind": "text",
        "notNull": true,
        "default": "user"
      },
      "content": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "citations": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      },
      "error": {
        "kind": "text"
      }
    }
  },
  {
    "name": "chapter_versions",
    "ddl": "CREATE TABLE chapter_versions (\n\tproject_id VARCHAR NOT NULL, \n\tchapter_id VARCHAR NOT NULL, \n\tid VARCHAR NOT NULL, \n\tposition INTEGER NOT NULL, \n\tsaved_at VARCHAR NOT NULL, \n\tlabel VARCHAR NOT NULL, \n\twords INTEGER NOT NULL, \n\tscenes TEXT NOT NULL, \n\tPRIMARY KEY (project_id, chapter_id, id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "chapter_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "position": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "saved_at": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "label": {
        "kind": "text",
        "notNull": true,
        "default": ""
      },
      "words": {
        "kind": "int",
        "notNull": true,
        "default": 0
      },
      "scenes": {
        "kind": "text",
        "notNull": true,
        "default": "[]"
      }
    }
  },
  {
    "name": "sweep_drafts",
    "ddl": "CREATE TABLE sweep_drafts (\n\tproject_id VARCHAR NOT NULL, \n\tdata TEXT NOT NULL, \n\tupdated_at VARCHAR NOT NULL, \n\tPRIMARY KEY (project_id), \n\tFOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE\n)",
    "indexes": [],
    "columns": {
      "project_id": {
        "kind": "text",
        "pk": true,
        "notNull": true
      },
      "data": {
        "kind": "text",
        "notNull": true,
        "default": "{}"
      },
      "updated_at": {
        "kind": "text",
        "notNull": true,
        "default": ""
      }
    }
  }
];
